import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "./ProjectCards";
import Particle from "../Particle";
import leaf from "../../Assets/Projects/leaf.png";
import emotion from "../../Assets/Projects/emotion.png";
import editor from "../../Assets/Projects/codeEditor.png";
import chatify from "../../Assets/Projects/chatify.png";
import suicide from "../../Assets/Projects/suicide.png";
import bitsOfCode from "../../Assets/Projects/blog.png";

function Projects() {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My Recent <strong className="purple">Works </strong>
        </h1>
        <p style={{ color: "white" }}>
          Here are a few projects I've worked on recently.
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={chatify}
              isBlog={false}
              title="Kolhapur Rides"
              description="A technology company focused on developing ride sharing solutions same like Uber,Rapido.Developed an online ride booking platform similar to Uber using HTML, CSS, JavaScript, and PHP.Implemented modules for OTP-based ride pickup verification and real-time driver assignment.Integrated a secure admin panel for driver registration and approval with autogenerated credentials."
              ghLink="https://github.com/siddhesh0109"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={bitsOfCode}
              isBlog={false}
              title="GainMeals Restourant"
              description="Built a responsive diet meal ordering website using HTML, CSS, JavaScript,
Node.js, and MongoDB.Offered plans like Weight Gain, Weight Loss, and High Protein with “Order Now” featureCreated backend APIs to handle orders and stored data in MongoDB . Included contact options with
WhatsApp and call integration."
              ghLink="https://github.com/siddhesh0109"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={editor}
              isBlog={false}
              title="Saree Shop"
              description="Developed a responsive E-Commerce website using HTML, CSS,
JavaScript with admin dashboard. Complete Frontend Part with admin dashboard"
              ghLink="https://github.com/siddhesh0109"
                     
            />
          </Col>

         
        </Row>
      </Container>
    </Container>
  );
}

export default Projects;
